_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 16
dry_run:
    value: false
epochs:
    value: 15
lr:
    value: 0.0002
project:
    value: clip-mm-decoder
repo:
    value: clip-mm-decoder
root:
    value: null
save_ckpt:
    value: checkpoints
